#version 450 core

const float PI = 3.141592653589793;

layout(local_size_x = 1, local_size_y = 1) in;

layout(rgba32f, binding = 0) writeonly uniform image2D imgOutput;

void main() {
    vec4 value = vec4(0.0, 0.0, 0.0, 1.0);
    ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);


	
    // value.x = max(float(texelCoord.x)/(gl_NumWorkGroups.x), 1.1);
    // value.y = max(float(texelCoord.y)/(gl_NumWorkGroups.y), 1.0);
    // float x = float(texelCoord.x)/gl_NumWorkGroups.x;
    // float y = float(texelCoord.y)/gl_NumWorkGroups.y;
    // value.y = cos((y+x)*20)*1;
	
    // imageStore(imgOutput, texelCoord, value);
    // float y = cos(texelCoord.x);
    value = vec4(float(texelCoord.x+texelCoord.y)/32, 0, 0, 1);
    // value = vec4(1, 0, 0, 1);
    imageStore(imgOutput, texelCoord, value);
}
